### ISSUE TITLE
Odd tilty organizaton

### ISSUE THREAD

**Issue by cal-miller** [BitBucketsFRC4183/FRC2015#1]
The way the tilty commands are organized might not make much sense.  Right now, there's a PresetTilty, a TiltGrabberDown and a TiltGrabberUp command.  That seems unhelpfully complex.  Instead, how about a single SetTiltyPosition command that can be set to an arbitrary value or a preset (Tilty.DOWN, Tilty.UP, etc.)

**Comment by cal-miller** [comment]
Also, I'm not clear what commands refer to the tilty and what is for the grabby.  I imagine you'd want SetTiltyPosition and SetGrabbyPosition.

**Comment by roryee** [comment]
Those were commands that were created without much thought and don't do anything. They were added as placeholders.
