### ISSUE TITLE
Improper MotionProfiler outputs for motions not along coordinate axes

### ISSUE THREAD

**Issue by cal-miller** [BitBucketsFRC4183/FRC2015#14]
Currently, the motion profiler generates profiles for x and y movement independently.  For the cases we have tested so far, of driving straight forwards or sideways, this is not a problem, since only one profile is nonzero.  

However, if the robot is commanded to move at an angle, it will accelerate at MAX_TRANS_ACCEL and cruise at MAX_TRANS_SPEED in both x and y.  That creates two issues:  First, given a long enough motion, the robot is being commanded to move faster than is physically possible; the robot speed will reach sqrt(2)\* MAX_TRANS_SPEED.

Even if robot speed stays below MAX_TRANS_SPEED, there is another issue: the x and y velocity-time functions are linearly independent for all cases where abs(xGoa|) != abs(yGoal).  What that means is that, although it will end up at the correct final position, the robot's path will not be a straight line, as we would expect.  For example, take xGoal = 1ft and yGoal = 10 ft.  The x profiler will take less time to complete than the y profiler, preventing the robot from following a straight line in the x-y plane, since all the x movement is completed before the y component.

For the profiler to produce correct movement, two conditions must be satisfied.  First, the maximum robot speed may not exceed MAX_TRANS_SPEED.  I'm not sure about how best to implement that.  Second, to ensure straight-line movement, the profiles must be such that for all time t, the profile x(t) must equal k \* the profile y(t), with k being a constant.  Basically, that requires that the program determines whether the x or y movement is longer, calculates the profile for the longer movement as it currently does, then multiplies that profile by (shorter distance)/(longer distance ) to find the profile for the shorter movement.

**Comment by cal-miller** [comment]
Edit:  This is not a problem with TrapezoidalMotionProfiler, but with DriveTranslation.

**Comment by roryee** [comment]
Made DrivePolar the main driving class with rectangular driving the wrapper class.
