### ISSUE TITLE
Integrate rotation with DriveTranslation

### ISSUE THREAD

**Issue by cal-miller** [BitBucketsFRC4183/FRC2015#15]
Since virtually all of the code for a rotational movement is identical to that for a translation, there is no reason for them to use different classes.  Odd behavior is possible when simultaneously translating and rotating, but the current code does not allow for rotation in autonomous at all.

If you choose to do that, changing the class name to DriveCartesian may make sense, since DriveTranslation suggests that rotation is not included.  Changing the name of DrivePolar would not be necessary.

**Comment by roryee** [comment]
I will add another class for rotation so that the odd behavior doesn't happen.

**Comment by cal-miller** [comment]
I thought of that, but a lot of code would need to be duplicated.  If rotation is integrated, it also makes some cool movements (that we'll likely never use) possible.

**Comment by roryee** [comment]
But if we accidentally try to make those cool movements, it will probably break,

**Comment by roryee** [comment]
Not going to happen, but added rotation.
