### ISSUE TITLE
Standardize units

### ISSUE THREAD

**Issue by cal-miller** [BitBucketsFRC4183/FRC2015#2]
We need to standardize the units used throughout the robot software to make our life easier.  I suggest decimal inches for all distances, radians for all angles and seconds for all times.  And pi, not tau.

Can we ensure that all the code conforms to these (or some other) standards?

**Comment by roryee** [comment]
Yes, but I would like to talk with the rest of the software team about how we handle some stuff internally and between functions.

**Comment by roryee** [comment]
Having everything in feet, radians, and seconds.
