### ISSUE TITLE
Remove "Relays" from RobotMap

### ISSUE THREAD

**Issue by cal-miller** [BitBucketsFRC4183/FRC2015#6]
In the branch DriveCode, which James has been working on, there is a section for relays, which includes a Compressor and Lights.  Although we have both of those components, neither is controlled with a relay; the compressor runs off the PCM and the lights from a special control board.

Can we get rid of the "Relays" section?

**Comment by roryee** [comment]
I fixed it so I wanna close it. Wah.

**Comment by cal-miller** [comment]
No
